import kaybee

import kaybee_bulma

from kaybee_bulma.siteconfig import SiteConfig

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

extensions = ['sphinx.ext.intersphinx',
              'kaybee',
              'kaybee_bulma',
              ]

# Add any paths that contain templates here, relative to this directory.
# templates_path = ['_templates'] + kaybee_bulma.get_html_templates_path()

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = kaybee_bulma.__title__
copyright = kaybee_bulma.__copyright__
author = kaybee_bulma.__author__

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = kaybee_bulma.__version__
# The full version, including alpha/beta/rc tags.
release = kaybee_bulma.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'kaybee_bulma'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Example configuration for intersphinx: refer to the Python standard library.
# intersphinx_mapping = {'https://docs.python.org/': None}

# kaybee config
kaybee_bulma_siteconfig = SiteConfig(
    logo=dict(
        img_file='kaybee_logo.png',
        alt='Kaybee Logo Alt'
    ),
    copyright='2018, All Rights Reserved',
    favicon='kaybee_logo.png',
    social_media=dict(
        twitter='xxx',
        github='xxx'
    ),
    description='Extensible Knowledge Base for Static Sites',
    navbar=dict(
        start=[
            dict(
                css_class='documentation',
                accent='primary',
                icon='book',
                label='Documentation',
                label_narrow='Docs',
                href='/documentation.html'
            )
        ]
    )
)

kaybee_settings = kaybee.KaybeeSettings(
    articles=dict(
        use_toctree=True
    )
)
